networks:
  arx_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  # Наш новый "Доверенный Дилер"
  trusted-dealer:
    build: .
    container_name: arx-trusted-dealer
    networks:
      arx_network:
        ipv4_address: 172.20.0.99
    command: python quic_test.py server --port 8012

  # Обычная нода
  arx-node:
    build: .
    container_name: arx-sim-node
    depends_on:
      - trusted-dealer
    networks:
      arx_network:
        ipv4_address: 172.20.0.100
    command: python quic_test.py client --host 172.20.0.99 --port 8012